<a href="https://colab.research.google.com/github/Vasudev-SN/MPEA_dataset/blob/master/Housing_data_Regression_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data',header=None,delim_whitespace=True)

In [ ]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [ ]:
data.describe

<bound method NDFrame.describe of           0     1      2   3      4      5     6       7   8      9     10  \
0    0.00632  18.0   2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3
1    0.02731   0.0   7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8
2    0.02729   0.0   7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8
3    0.03237   0.0   2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7
4    0.06905   0.0   2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7
..       ...   ...    ...  ..    ...    ...   ...     ...  ..    ...   ...
501  0.06263   0.0  11.93   0  0.573  6.593  69.1  2.4786   1  273.0  21.0
502  0.04527   0.0  11.93   0  0.573  6.120  76.7  2.2875   1  273.0  21.0
503  0.06076   0.0  11.93   0  0.573  6.976  91.0  2.1675   1  273.0  21.0
504  0.10959   0.0  11.93   0  0.573  6.794  89.3  2.3889   1  273.0  21.0
505  0.04741   0.0  11.93   0  0.573  6.030  80.8  2.5050   1  273.0  21.0

         11    12    13
0    396.90  4.98  24.0
1    396.90  9.14  21.6
2    392.83  4.03  34.7
3    394.63  2.94  33.4
4    396.90  5.33  36.2
..      ...   ...   ...
501  391.99  9.67  22.4
502  396.90  9.08  20.6
503  396.90  5.64  23.9
504  393.45  6.48  22.0
505  396.90  7.88  11.9

[506 rows x 14 columns]>

In [ ]:
from keras.layers import Dense, Activation
from keras import Sequential
import tensorflow 
import keras

In [ ]:
data.isnull()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,False,False,False,False,False,False,False,False,False,False,False,False,False,False
502,False,False,False,False,False,False,False,False,False,False,False,False,False,False
503,False,False,False,False,False,False,False,False,False,False,False,False,False,False
504,False,False,False,False,False,False,False,False,False,False,False,False,False,False
505,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
data.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [ ]:
X = data.values[:,0:13]
Y=data.values[:,13]
# Y = data[13]
type(X)

numpy.ndarray

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(13, input_shape=(13,), kernel_initializer='normal'))
model.add(Dense(1, kernel_initializer='normal' ))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_2 (Dense)             (None, 13)                182

 dense_3 (Dense)             (None, 1)                 14

=================================================================
Total params: 196
Trainable params: 196
Non-trainable params: 0
_________________________________________________________________

In [ ]:
import tensorflow as tf

In [ ]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [ ]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [ ]:
Y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21.5, 19.6, 15.3, 19.4,
       17. , 15.6, 13.1, 41.3, 24.3, 23.3, 27. , 50. , 50. , 50. , 22.7,
       25. , 50. , 23.8, 23.8, 22.3, 17.4, 19.1, 23.1, 23.6, 22.6, 29.4,
       23.2, 24.6, 29.9, 37.2, 39.8, 36.2, 37.9, 32.5, 26.4, 29.6, 50. ,
       32. , 29.8, 34.9, 37. , 30.5, 36.4, 31.1, 29.1, 50. , 33.3, 30.3,
       34.6, 34.9, 32.9, 24.1, 42.3, 48.5, 50. , 22.6, 24.4, 22.5, 24.4,
       20. , 21.7, 19.3, 22.4, 28.1, 23.7, 25. , 23.3, 28.7, 21.5, 23. ,
       26.7, 21.7, 27.5, 30.1, 44.8, 50. , 37.6, 31.6, 46.7, 31.5, 24.3,
       31.7, 41.7, 48.3, 29. , 24. , 25.1, 31.5, 23.7, 23.3, 22. , 20.1,
       22.2, 23.7, 17.6, 18.5, 24.3, 20.5, 24.5, 26.2, 24.4, 24.8, 29.6,
       42.8, 21.9, 20.9, 44. , 50. , 36. , 30.1, 33.8, 43.1, 48.8, 31. ,
       36.5, 22.8, 30.7, 50. , 43.5, 20.7, 21.1, 25.2, 24.4, 35.2, 32.4,
       32. , 33.2, 33.1, 29.1, 35.1, 45.4, 35.4, 46. , 50. , 32.2, 22. ,
       20.1, 23.2, 22.3, 24.8, 28.5, 37.3, 27.9, 23.9, 21.7, 28.6, 27.1,
       20.3, 22.5, 29. , 24.8, 22. , 26.4, 33.1, 36.1, 28.4, 33.4, 28.2,
       22.8, 20.3, 16.1, 22.1, 19.4, 21.6, 23.8, 16.2, 17.8, 19.8, 23.1,
       21. , 23.8, 23.1, 20.4, 18.5, 25. , 24.6, 23. , 22.2, 19.3, 22.6,
       19.8, 17.1, 19.4, 22.2, 20.7, 21.1, 19.5, 18.5, 20.6, 19. , 18.7,
       32.7, 16.5, 23.9, 31.2, 17.5, 17.2, 23.1, 24.5, 26.6, 22.9, 24.1,
       18.6, 30.1, 18.2, 20.6, 17.8, 21.7, 22.7, 22.6, 25. , 19.9, 20.8,
       16.8, 21.9, 27.5, 21.9, 23.1, 50. , 50. , 50. , 50. , 50. , 13.8,
       13.8, 15. , 13.9, 13.3, 13.1, 10.2, 10.4, 10.9, 11.3, 12.3,  8.8,
        7.2, 10.5,  7.4, 10.2, 11.5, 15.1, 23.2,  9.7, 13.8, 12.7, 13.1,
       12.5,  8.5,  5. ,  6.3,  5.6,  7.2, 12.1,  8.3,  8.5,  5. , 11.9,
       27.9, 17.2, 27.5, 15. , 17.2, 17.9, 16.3,  7. ,  7.2,  7.5, 10.4,
        8.8,  8.4, 16.7, 14.2, 20.8, 13.4, 11.7,  8.3, 10.2, 10.9, 11. ,
        9.5, 14.5, 14.1, 16.1, 14.3, 11.7, 13.4,  9.6,  8.7,  8.4, 12.8,
       10.5, 17.1, 18.4, 15.4, 10.8, 11.8, 14.9, 12.6, 14.1, 13. , 13.4,
       15.2, 16.1, 17.8, 14.9, 14.1, 12.7, 13.5, 14.9, 20. , 16.4, 17.7,
       19.5, 20.2, 21.4, 19.9, 19. , 19.1, 19.1, 20.1, 19.9, 19.6, 23.2,
       29.8, 13.8, 13.3, 16.7, 12. , 14.6, 21.4, 23. , 23.7, 25. , 21.8,
       20.6, 21.2, 19.1, 20.6, 15.2,  7. ,  8.1, 13.6, 20.1, 21.8, 24.5,
       23.1, 19.7, 18.3, 21.2, 17.5, 16.8, 22.4, 20.6, 23.9, 22. , 11.9])

In [ ]:
X.shape

(506, 13)

In [ ]:
Y.shape

(506,)

In [ ]:
X.ndim

2

In [ ]:
Y.ndim

1

In [ ]:
model.fit(X,Y,epochs=70,verbose=1)

Epoch 1/70
16/16 [==============================] - 1s 2ms/step - loss: 481.1891
Epoch 2/70
16/16 [==============================] - 0s 2ms/step - loss: 181.0927
Epoch 3/70
16/16 [==============================] - 0s 2ms/step - loss: 120.8294
Epoch 4/70
16/16 [==============================] - 0s 3ms/step - loss: 108.4330
Epoch 5/70
16/16 [==============================] - 0s 2ms/step - loss: 98.3567
Epoch 6/70
16/16 [==============================] - 0s 2ms/step - loss: 90.7979
Epoch 7/70
16/16 [==============================] - 0s 2ms/step - loss: 84.3610
Epoch 8/70
16/16 [==============================] - 0s 3ms/step - loss: 79.3037
Epoch 9/70
16/16 [==============================] - 0s 5ms/step - loss: 75.3540
Epoch 10/70
16/16 [==============================] - 0s 6ms/step - loss: 72.9481
Epoch 11/70
16/16 [==============================] - 0s 3ms/step - loss: 71.5833
Epoch 12/70
16/16 [==============================] - 0s 3ms/step - loss: 70.6831
Epoch 13/70
16/16 [==============================] - 0s 3ms/step - loss: 69.9861
Epoch 14/70
16/16 [==============================] - 0s 3ms/step - loss: 69.6807
Epoch 15/70
16/16 [==============================] - 0s 3ms/step - loss: 69.2246
Epoch 16/70
16/16 [==============================] - 0s 4ms/step - loss: 68.6926
Epoch 17/70
16/16 [==============================] - 0s 3ms/step - loss: 68.4417
Epoch 18/70
16/16 [==============================] - 0s 3ms/step - loss: 68.0815
Epoch 19/70
16/16 [==============================] - 0s 2ms/step - loss: 67.7078
Epoch 20/70
16/16 [==============================] - 0s 2ms/step - loss: 67.0485
Epoch 21/70
16/16 [==============================] - 0s 3ms/step - loss: 66.7913
Epoch 22/70
16/16 [==============================] - 0s 3ms/step - loss: 66.5569
Epoch 23/70
16/16 [==============================] - 0s 2ms/step - loss: 66.2753
Epoch 24/70
16/16 [==============================] - 0s 2ms/step - loss: 65.6834
Epoch 25/70
16/16 [==============================] - 0s 2ms/step - loss: 65.1088
Epoch 26/70
16/16 [==============================] - 0s 3ms/step - loss: 64.6951
Epoch 27/70
16/16 [==============================] - 0s 3ms/step - loss: 64.4821
Epoch 28/70
16/16 [==============================] - 0s 2ms/step - loss: 63.7943
Epoch 29/70
16/16 [==============================] - 0s 2ms/step - loss: 64.0287
Epoch 30/70
16/16 [==============================] - 0s 2ms/step - loss: 64.8663
Epoch 31/70
16/16 [==============================] - 0s 2ms/step - loss: 62.4417
Epoch 32/70
16/16 [==============================] - 0s 2ms/step - loss: 62.4028
Epoch 33/70
16/16 [==============================] - 0s 2ms/step - loss: 61.4081
Epoch 34/70
16/16 [==============================] - 0s 2ms/step - loss: 61.4174
Epoch 35/70
16/16 [==============================] - 0s 2ms/step - loss: 61.7203
Epoch 36/70
16/16 [==============================] - 0s 2ms/step - loss: 61.3425
Epoch 37/70
16/16 [==============================] - 0s 2ms/step - loss: 59.9322
Epoch 38/70
16/16 [==============================] - 0s 2ms/step - loss: 60.8075
Epoch 39/70
16/16 [==============================] - 0s 2ms/step - loss: 58.8468
Epoch 40/70
16/16 [==============================] - 0s 2ms/step - loss: 58.0326
Epoch 41/70
16/16 [==============================] - 0s 2ms/step - loss: 57.4413
Epoch 42/70
16/16 [==============================] - 0s 4ms/step - loss: 57.4545
Epoch 43/70
16/16 [==============================] - 0s 2ms/step - loss: 56.3055
Epoch 44/70
16/16 [==============================] - 0s 2ms/step - loss: 56.1331
Epoch 45/70
16/16 [==============================] - 0s 2ms/step - loss: 56.1692
Epoch 46/70
16/16 [==============================] - 0s 2ms/step - loss: 54.8631
Epoch 47/70
16/16 [==============================] - 0s 2ms/step - loss: 54.5456
Epoch 48/70
16/16 [==============================] - 0s 2ms/step - loss: 54.4931
Epoch 49/70
16/16 [==============================] - 0s 2ms/step - loss: 54.6621
Epoch 50/70
16/16 [==============================] - 0s 2ms/step - loss: 52.8950
Epoch 51/70
16/16 [==============================] - 0s 2ms/step - loss: 52.7016
Epoch 52/70
16/16 [==============================] - 0s 2ms/step - loss: 52.2172
Epoch 53/70
16/16 [==============================] - 0s 2ms/step - loss: 52.0130
Epoch 54/70
16/16 [==============================] - 0s 2ms/step - loss: 51.0644
Epoch 55/70
16/16 [==============================] - 0s 2ms/step - loss: 51.9606
Epoch 56/70
16/16 [==============================] - 0s 2ms/step - loss: 50.2683
Epoch 57/70
16/16 [==============================] - 0s 2ms/step - loss: 49.9547
Epoch 58/70
16/16 [==============================] - 0s 3ms/step - loss: 49.3035
Epoch 59/70
16/16 [==============================] - 0s 3ms/step - loss: 48.8298
Epoch 60/70
16/16 [==============================] - 0s 2ms/step - loss: 49.0138
Epoch 61/70
16/16 [==============================] - 0s 2ms/step - loss: 48.1528
Epoch 62/70
16/16 [==============================] - 0s 2ms/step - loss: 47.6620
Epoch 63/70
16/16 [==============================] - 0s 2ms/step - loss: 47.1958
Epoch 64/70
16/16 [==============================] - 0s 2ms/step - loss: 46.9090
Epoch 65/70
16/16 [==============================] - 0s 2ms/step - loss: 47.3252
Epoch 66/70
16/16 [==============================] - 0s 2ms/step - loss: 50.8688
Epoch 67/70
16/16 [==============================] - 0s 2ms/step - loss: 46.4427
Epoch 68/70
16/16 [==============================] - 0s 2ms/step - loss: 45.6084
Epoch 69/70
16/16 [==============================] - 0s 3ms/step - loss: 45.9719
Epoch 70/70
16/16 [==============================] - 0s 2ms/step - loss: 45.5486

In [ ]:
y_pred=model.predict(X)

16/16 [==============================] - 0s 4ms/step

In [ ]:
y_pred

array([[28.269648  ],
       [24.781065  ],
       [26.687225  ],
       [26.485193  ],
       [25.929708  ],
       [25.944475  ],
       [22.064308  ],
       [20.810629  ],
       [13.228684  ],
       [20.677906  ],
       [19.724302  ],
       [23.298794  ],
       [16.649     ],
       [24.033035  ],
       [24.58644   ],
       [23.201035  ],
       [21.292892  ],
       [21.444439  ],
       [14.900607  ],
       [22.407806  ],
       [18.192408  ],
       [22.976347  ],
       [20.148079  ],
       [19.991407  ],
       [21.892824  ],
       [17.477629  ],
       [21.84171   ],
       [17.65791   ],
       [24.431059  ],
       [24.037266  ],
       [16.251795  ],
       [24.12133   ],
       [ 7.171622  ],
       [19.144484  ],
       [14.344161  ],
       [23.564352  ],
       [20.935637  ],
       [21.312384  ],
       [19.12721   ],
       [30.954676  ],
       [32.170105  ],
       [19.510166  ],
       [18.794683  ],
       [18.091528  ],
       [19.964193  ],
       [18.84134   ],
       [16.185587  ],
       [18.620253  ],
       [11.286425  ],
       [17.774336  ],
       [20.430456  ],
       [25.036688  ],
       [23.740538  ],
       [21.31719   ],
       [27.33625   ],
       [32.989285  ],
       [32.76015   ],
       [35.738228  ],
       [24.542986  ],
       [24.905573  ],
       [24.094091  ],
       [25.641489  ],
       [29.127584  ],
       [24.837875  ],
       [26.615963  ],
       [30.505825  ],
       [27.832067  ],
       [21.141226  ],
       [19.236956  ],
       [21.927465  ],
       [18.433226  ],
       [16.920546  ],
       [19.400064  ],
       [17.485321  ],
       [18.568436  ],
       [20.8642    ],
       [21.591948  ],
       [20.06939   ],
       [19.592615  ],
       [20.050589  ],
       [26.210981  ],
       [28.71578   ],
       [24.837107  ],
       [25.541204  ],
       [21.61323   ],
       [24.541418  ],
       [18.828384  ],
       [23.06823   ],
       [28.78823   ],
       [26.202305  ],
       [23.849688  ],
       [25.132933  ],
       [25.170168  ],
       [23.764946  ],
       [25.987387  ],
       [23.476072  ],
       [22.444826  ],
       [29.330307  ],
       [25.335917  ],
       [26.148874  ],
       [25.745173  ],
       [26.085394  ],
       [14.013719  ],
       [23.428787  ],
       [24.409147  ],
       [22.15452   ],
       [20.208952  ],
       [22.496008  ],
       [25.489468  ],
       [22.336216  ],
       [20.235804  ],
       [24.827045  ],
       [21.388235  ],
       [21.235987  ],
       [24.353373  ],
       [19.458849  ],
       [22.165443  ],
       [24.359428  ],
       [17.86878   ],
       [19.982609  ],
       [17.756628  ],
       [19.03737   ],
       [17.47623   ],
       [12.499684  ],
       [18.010246  ],
       [19.352427  ],
       [10.52366   ],
       [20.193367  ],
       [22.335068  ],
       [19.339327  ],
       [24.197897  ],
       [24.18216   ],
       [24.693771  ],
       [21.575453  ],
       [15.839053  ],
       [21.054945  ],
       [19.79856   ],
       [22.748539  ],
       [17.72952   ],
       [19.951195  ],
       [15.3732815 ],
       [ 8.520361  ],
       [13.508622  ],
       [12.807833  ],
       [10.436271  ],
       [ 4.7070317 ],
       [11.840632  ],
       [ 9.940829  ],
       [ 9.520614  ],
       [14.316712  ],
       [20.74548   ],
       [20.066162  ],
       [20.35263   ],
       [15.547169  ],
       [19.074219  ],
       [ 9.352593  ],
       [ 8.488179  ],
       [27.365368  ],
       [25.490114  ],
       [25.558266  ],
       [25.857744  ],
       [29.301226  ],
       [31.562523  ],
       [30.524286  ],
       [22.311646  ],
       [18.346577  ],
       [28.576834  ],
       [14.870541  ],
       [19.993055  ],
       [20.937027  ],
       [17.283518  ],
       [21.002602  ],
       [21.757555  ],
       [25.605696  ],
       [23.134571  ],
       [22.642221  ],
       [20.67217   ],
       [26.303349  ],
       [26.15734   ],
       [26.03744   ],
       [27.424248  ],
       [22.917301  ],
       [29.784252  ],
       [29.29204   ],
       [22.255796  ],
       [20.811789  ],
       [26.332142  ],
       [27.848608  ],
       [27.5094    ],
       [28.882095  ],
       [26.496075  ],
       [28.050089  ],
       [29.10552   ],
       [26.991081  ],
       [27.673906  ],
       [33.770367  ],
       [32.629585  ],
       [28.232338  ],
       [31.185806  ],
       [32.96255   ],
       [32.552162  ],
       [30.674974  ],
       [32.157055  ],
       [34.648438  ],
       [35.178112  ],
       [17.201225  ],
       [20.555758  ],
       [17.370628  ],
       [19.049385  ],
       [17.727736  ],
       [21.12087   ],
       [15.891414  ],
       [17.69485   ],
       [19.191952  ],
       [ 1.2230732 ],
       [20.348219  ],
       [19.00693   ],
       [24.253048  ],
       [20.206572  ],
       [25.256237  ],
       [26.8495    ],
       [18.824257  ],
       [25.446423  ],
       [26.495949  ],
       [29.219522  ],
       [29.545109  ],
       [30.71937   ],
       [26.741156  ],
       [22.244833  ],
       [22.185104  ],
       [21.383135  ],
       [27.486162  ],
       [29.903671  ],
       [28.316607  ],
       [24.418682  ],
       [21.23886   ],
       [25.410692  ],
       [27.741701  ],
       [23.349215  ],
       [25.415762  ],
       [24.436821  ],
       [24.506521  ],
       [23.44417   ],
       [22.81627   ],
       [24.30086   ],
       [20.186722  ],
       [23.06677   ],
       [26.710958  ],
       [24.01134   ],
       [23.493668  ],
       [23.39126   ],
       [23.809347  ],
       [24.352978  ],
       [25.679644  ],
       [30.413094  ],
       [27.162582  ],
       [34.392445  ],
       [31.117025  ],
       [29.61149   ],
       [30.21046   ],
       [26.732359  ],
       [29.165213  ],
       [30.812647  ],
       [27.022335  ],
       [28.6042    ],
       [23.044733  ],
       [23.05814   ],
       [27.003424  ],
       [28.07149   ],
       [22.62744   ],
       [19.947557  ],
       [22.088774  ],
       [25.929577  ],
       [27.483166  ],
       [29.355001  ],
       [29.924423  ],
       [29.44278   ],
       [28.322622  ],
       [25.69904   ],
       [24.970146  ],
       [29.49375   ],
       [25.686735  ],
       [28.90014   ],
       [34.431545  ],
       [29.825644  ],
       [26.5846    ],
       [24.725243  ],
       [27.099646  ],
       [28.375013  ],
       [23.950228  ],
       [33.035233  ],
       [33.03419   ],
       [31.483562  ],
       [17.680908  ],
       [18.916227  ],
       [20.9574    ],
       [22.102442  ],
       [16.795431  ],
       [28.477911  ],
       [28.116774  ],
       [31.75906   ],
       [24.510546  ],
       [22.242931  ],
       [25.290989  ],
       [27.106462  ],
       [27.128618  ],
       [30.877272  ],
       [29.636023  ],
       [28.40082   ],
       [23.67599   ],
       [15.195591  ],
       [23.87658   ],
       [23.98174   ],
       [25.829092  ],
       [25.646826  ],
       [22.634367  ],
       [18.524567  ],
       [19.062132  ],
       [22.637842  ],
       [20.018353  ],
       [23.859453  ],
       [24.262094  ],
       [23.007864  ],
       [22.465626  ],
       [23.27253   ],
       [21.22323   ],
       [22.032122  ],
       [18.975708  ],
       [18.525387  ],
       [19.432524  ],
       [19.525007  ],
       [20.594023  ],
       [22.26549   ],
       [23.355783  ],
       [22.661346  ],
       [21.45052   ],
       [21.354603  ],
       [22.215935  ],
       [21.345446  ],
       [21.35139   ],
       [23.037323  ],
       [28.654993  ],
       [23.534586  ],
       [30.80286   ],
       [29.366535  ],
       [20.915384  ],
       [19.061901  ],
       [31.389936  ],
       [31.163263  ],
       [28.125029  ],
       [29.07451   ],
       [29.951399  ],
       [26.856976  ],
       [33.760834  ],
       [29.341385  ],
       [30.693548  ],
       [21.591791  ],
       [25.088715  ],
       [25.306004  ],
       [23.292692  ],
       [26.89007   ],
       [22.04134   ],
       [25.789461  ],
       [22.167723  ],
       [29.85663   ],
       [24.789856  ],
       [20.159021  ],
       [13.138676  ],
       [30.220913  ],
       [31.462791  ],
       [32.73557   ],
       [25.890793  ],
       [25.42319   ],
       [ 8.831943  ],
       [ 5.257358  ],
       [23.509857  ],
       [15.330293  ],
       [19.222464  ],
       [15.302533  ],
       [17.511353  ],
       [11.450654  ],
       [18.457436  ],
       [17.05682   ],
       [16.544027  ],
       [ 5.3918386 ],
       [10.853703  ],
       [11.428548  ],
       [ 8.247891  ],
       [10.415015  ],
       [18.844353  ],
       [21.448599  ],
       [18.663996  ],
       [14.724526  ],
       [22.46454   ],
       [21.107182  ],
       [21.796644  ],
       [20.458775  ],
       [19.620314  ],
       [ 8.628397  ],
       [ 8.442964  ],
       [13.215697  ],
       [19.153667  ],
       [19.057028  ],
       [17.15975   ],
       [ 6.557719  ],
       [ 9.815032  ],
       [13.950555  ],
       [22.235958  ],
       [12.3096695 ],
       [12.204817  ],
       [ 7.3193564 ],
       [ 6.133038  ],
       [-4.8583627 ],
       [10.261651  ],
       [-7.948379  ],
       [-0.04163428],
       [ 2.1123261 ],
       [ 2.2135165 ],
       [-1.935745  ],
       [ 3.5073938 ],
       [20.475384  ],
       [19.81037   ],
       [18.201435  ],
       [ 2.5662644 ],
       [ 4.6470127 ],
       [ 1.8821688 ],
       [ 4.951719  ],
       [ 4.643849  ],
       [ 6.3343997 ],
       [ 5.0824847 ],
       [ 9.280911  ],
       [ 8.803887  ],
       [12.691409  ],
       [11.487727  ],
       [11.780467  ],
       [ 7.191488  ],
       [ 7.199088  ],
       [ 1.300945  ],
       [-2.9860375 ],
       [16.950806  ],
       [15.665507  ],
       [19.656155  ],
       [22.660965  ],
       [20.449865  ],
       [10.89771   ],
       [ 4.353902  ],
       [18.763605  ],
       [21.648722  ],
       [21.047173  ],
       [17.346565  ],
       [ 7.7404366 ],
       [20.602064  ],
       [21.088713  ],
       [22.226     ],
       [ 6.9075804 ],
       [ 8.495688  ],
       [ 6.310884  ],
       [ 6.2033553 ],
       [16.689333  ],
       [22.117908  ],
       [17.250671  ],
       [22.954094  ],
       [22.617615  ],
       [25.978752  ],
       [21.043068  ],
       [16.725708  ],
       [ 7.7218575 ],
       [16.626188  ],
       [16.164862  ],
       [18.079031  ],
       [21.331867  ],
       [24.3696    ],
       [21.819757  ],
       [22.41209   ],
       [18.792818  ],
       [13.899336  ],
       [20.82447   ],
       [13.353158  ],
       [20.154964  ],
       [22.191467  ],
       [22.90093   ],
       [26.213526  ],
       [27.20495   ],
       [20.486422  ],
       [18.030977  ],
       [21.714024  ],
       [21.447683  ],
       [20.809721  ],
       [19.092226  ],
       [13.878789  ],
       [ 8.887988  ],
       [19.902668  ],
       [21.71638   ],
       [20.260918  ],
       [18.10464   ],
       [13.667504  ],
       [15.896325  ],
       [20.677835  ],
       [21.036852  ],
       [20.117151  ],
       [21.624813  ],
       [23.43596   ],
       [24.509058  ],
       [28.890991  ],
       [27.910517  ],
       [25.709702  ]], dtype=float32)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
model.evaluate(x=X,y=y_pred)

16/16 [==============================] - 0s 3ms/step - loss: 2.7352e-12

2.7352243733846926e-12